// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/user-management/getUserList': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user-management/getUserList.get').default>>>>
    }
    '/user-management/userAuth': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user-management/userAuth.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}