// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/11/5 11:58:00
const configMerger = require("C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/plugins/**/*.{js,ts,mjs}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/composables/**/*.{js,ts,mjs}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/utils/**/*.{js,ts,mjs}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/portfolio_ver2.2/Nuxt3_frontend/app.config.{js,ts,mjs}"] } }));

module.exports = config
