// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/10/23 10:49:06
const configMerger = require("C:/Codes/Study/outizaisan_ver_1/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Codes/Study/outizaisan_ver_1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/outizaisan_ver_1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/outizaisan_ver_1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/outizaisan_ver_1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/outizaisan_ver_1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/outizaisan_ver_1/plugins/**/*.{js,ts,mjs}","C:/Codes/Study/outizaisan_ver_1/composables/**/*.{js,ts,mjs}","C:/Codes/Study/outizaisan_ver_1/utils/**/*.{js,ts,mjs}","C:/Codes/Study/outizaisan_ver_1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/outizaisan_ver_1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Codes/Study/outizaisan_ver_1/app.config.{js,ts,mjs}"] } }));

module.exports = config
